.dh_title {

}

.dh_logoSmall {
	padding: 12px 5px 0 5px;
	height: 25px;
	width: 25px;
	margin-top: -10px;
}

.dh_title h3 {
	text-transform: uppercase;
	position: relative;
	top: -8px;
}

td.collision {
	color: red !important;
}

.stdTableContainer {
	overflow: auto; 
	width: 100%; 
	height: 400px; 
	margin: 0
}

.pbSubheader {
	background-color: #8a9ebe !important;
	border-color: #8a9ebe !important;
}

td.width-50 {
	width: 50%;
}

.width-50 .apexp {
	height: 100%;
}